on: push

name: "Main workflow"
permissions: {}

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Check .md files grammar
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install python  
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install proselint
      - name: Write good action step 
        uses: ./.github/actions/write-good-action
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
